# Generated by Django 5.1 on 2024-09-17 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawCurrencySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crypto_id", models.CharField(max_length=128)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CurrencySpecificDatem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crypto_id", models.CharField(db_index=True, max_length=128)),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "usd"), ("EUR", "eur")], db_index=True
                    ),
                ),
                ("value", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "raw_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_collection.rawcurrencysnapshot",
                    ),
                ),
            ],
        ),
    ]
