# Generated by Django 5.1 on 2024-09-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_collection", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyspecificdatem",
            name="currency",
            field=models.CharField(db_index=True),
        ),
    ]
