# Generated by Django 5.1 on 2024-09-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_collection", "0002_alter_currencyspecificdatem_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyspecificdatem",
            name="value",
            field=models.FloatField(null=True),
        ),
    ]
